services:
  db:
    image: mariadb
    container_name: cherry-booker-main-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD:
      MARIADB_DATABASE: test
      MARIADB_USER:
      MARIADB_PASSWORD:
    volumes:
      - db-data:/var/lib/mariadb/data
    ports:
      - "3306:3306"

  app:
    build:
      context: .
    container_name: cherrybooker-main-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/test
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"                         #host is 8080, conatiner is 8080.

volumes:
  db-data:
